let

content = [
    household= [
      income= 52000,
      people= {
        [
          age = 27,
          aptc_eligible= true,
          gender= "Female",
          uses_tobacco= false
        ]
      }
    ],
    market= "Individual",
    place= [
      countyfips= "22033",
      state= "LA",
      zipcode= "70810"
    ],
    year= 2023,
    limit=10,
    offset=10,
    order="asc"
],
JsonDoc = Json.FromValue(content),
URL = "https://marketplace.api.healthcare.gov/api/v1/plans/search?apikey=" & CMSKey,
Headers = [#"Content-Type"="application/json"],
WebContent = Web.Contents(URL, [Headers=Headers, Content=JsonDoc]),


// Based on work from https://eriksvensen.wordpress.com/2014/09/15/specifying-json-query-in-power-query-example-statistics-sweden/
    Source = Json.Document(WebContent),
    // Based on work from https://eriksvensen.wordpress.com/2014/09/15/specifying-json-query-in-power-query-example-statistics-sweden/
    plans = Source[plans],
    #"Converted to Table" = Table.FromList(plans, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "name", "premium", "premium_w_credit", "ehb_premium", "pediatric_ehb_premium", "aptc_eligible_premium", "metal_level", "type", "state", "benefits", "deductibles", "tiered_deductibles", "disease_mgmt_programs", "has_national_network", "market", "max_age_child", "moops", "tiered_moops", "product_division", "benefits_url", "brochure_url", "formulary_url", "network_url", "issuer", "hsa_eligible", "insurance_market", "specialist_referral_required", "oopc", "tobacco_lookback", "suppression_state", "guaranteed_rate", "simple_choice", "quality_rating", "is_ineligible", "rx_3mo_mail_order", "covers_nonhyde_abortion", "service_area_id"}, {"id", "name", "premium", "premium_w_credit", "ehb_premium", "pediatric_ehb_premium", "aptc_eligible_premium", "metal_level", "type", "state", "benefits", "deductibles", "tiered_deductibles", "disease_mgmt_programs", "has_national_network", "market", "max_age_child", "moops", "tiered_moops", "product_division", "benefits_url", "brochure_url", "formulary_url", "network_url", "issuer", "hsa_eligible", "insurance_market", "specialist_referral_required", "oopc", "tobacco_lookback", "suppression_state", "guaranteed_rate", "simple_choice", "quality_rating", "is_ineligible", "rx_3mo_mail_order", "covers_nonhyde_abortion", "service_area_id"})
in
    #"Expanded Column1"